on: 
  workflow_dispatch:
    inputs:
      Name:
        description: 'Raihan'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Log level: ${{ github.event.inputs.Name }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 
